#!/bin/bash
export LC_ALL='en_US.UTF-8'
export LANG='en_US.UTF-8'

export EDITOR="nvim"
export VISUAL=$EDITOR
export USE_EDITOR=$EDITOR
export TERMINAL="alacritty"
export FILE="ranger"
export READER="zathura"
export BROWSER="brave"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export MYVIMRC="${XDG_CONFIG_HOME:-$HOME/.config}/nvim/init.vim"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# use nvim as Man pager `:h Man`
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# Other program settings
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME="gtk2"	# Have QT use gtk2 theme.

export NVM_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/.nvm"

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
