#!/bin/sh
# Run this file when starting WM.

#picom -b &            # for transparency
dunst &               # for notifications
nm-applet &           # for network-applet on status bar
blueman-applet &      # for bluetooth-applet on status bar
unclutter &           # for removing mouse when idle
telegram-desktop &    # for telegram
#polybar-launcher &    # start polybar
# sxhkd &
