# Autogenerated config.py
# Documentation:
#   qute://help/configuring.html
#   qute://help/settings.html

# Uncomment this to still load settings configured via autoconfig.yml
# config.load_autoconfig()

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'file://*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'chrome://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'qute://*/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://raw.githubusercontent.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'https://raw.githubusercontent.com/qutebrowser/qutebrowser/master/doc/img/cheatsheet-big.png')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', False, 'https://www.youtube.com/watch?v=hQ5RDg0Y9yU')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, '*://www.youtube.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'https://www.netflix.com/browse/genre/83')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', False, '*://www.netflix.com/*')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'https://www.netflix.com/search?q=f')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'https://www.ebay.de/itm/Herpa-Wings-TAP-Portugal-A330-200-CS-TOF-1-500/153227020969?ssPageName=STRK%3AMEBIDX%3AIT&_trksid=p2060353.m1438.l2649')

# Enable JavaScript.
# Type: Bool
config.set('content.javascript.enabled', True, 'https://www.ebay.de/myb/Summary?MyEbayBeta&MyEbay=&gbh=1&guest=1')

# Enable plugins in Web pages.
# Type: Bool
config.set('content.plugins', True, '*://raw.githubusercontent.com/*')

# Position of the tab bar.
# Type: Position
# Valid values:
#   - top
#   - bottom
#   - left
#   - right
c.tabs.position = 'top'

# Default monospace fonts. Whenever "monospace" is used in a font
# setting, it's replaced with the fonts listed here.
# Type: Font
c.fonts.monospace = '"xos4 Terminus", Terminus, Monospace, "DejaVu Sans Mono", Monaco, "Bitstream Vera Sans Mono", "Andale Mono", "Courier New", Courier, "Liberation Mono", monospace, Fixed, Consolas, Terminal'

# Font used in the completion widget.
# Type: Font
c.fonts.completion.entry = '10pt monospace'

# Font used in the completion categories.
# Type: Font
c.fonts.completion.category = 'bold 10pt monospace'

# Font used for the debugging console.
# Type: QtFont
c.fonts.debug_console = '10pt monospace'

# Font used for the downloadbar.
# Type: Font
c.fonts.downloads = '10pt monospace'

# Font used for the hints.
# Type: Font
c.fonts.hints = 'bold 10pt monospace'

# Font used in the keyhint widget.
# Type: Font
c.fonts.keyhint = '10pt monospace'

# Font used for error messages.
# Type: Font
c.fonts.messages.error = '10pt monospace'

# Font used for info messages.
# Type: Font
c.fonts.messages.info = '10pt monospace'

# Font used for warning messages.
# Type: Font
c.fonts.messages.warning = '10pt monospace'

# Font used for prompts.
# Type: Font
c.fonts.prompts = '10pt sans-serif'

# Font used in the statusbar.
# Type: Font
c.fonts.statusbar = '10pt monospace'

# Font used in the tab bar.
# Type: QtFont
c.fonts.tabs = 'bold 12pt monospace'

# Font family for standard fonts.
# Type: FontFamily
c.fonts.web.family.standard = None

# This setting can be used to map keys to other keys. When the key used
# as dictionary-key is pressed, the binding for the key used as
# dictionary-value is invoked instead. This is useful for global
# remappings of keys, for example to map Ctrl-[ to Escape. Note that
# when a key is bound (via `bindings.default` or `bindings.commands`),
# the mapping is ignored.
# Type: Dict
c.bindings.key_mappings = {'<Ctrl+[>': '<Escape>', '<Ctrl+6>': '<Ctrl+^>', '<Ctrl+m>': '<Return>', '<Ctrl+j>': '<Return>', '<Shift+Return>': '<Return>', '<Enter>': '<Return>', '<Shift+Enter>': '<Return>', '<Ctrl+Enter>': '<Ctrl+Return>'}

config.bind('J', 'tab-prev')
config.bind('K', 'tab-next')

c.url.searchengines = {
    'DEFAULT': 'https://duckduckgo.com/?q={}',
    'wa': 'https://wiki.archlinux.org/?search={}',
    'gh': 'https://github.com/{}',
}
